name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Race
        run: go test -v -race ./...
        continue-on-error: true
      - name: Test
        run: go test -v -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./...
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        flags:
        - ""
        - -tags headless
        cgo: ["0", "1"]
        exclude:
        # cgo is currently required by the upstream SQLite driver.
        # This exception should be removed if/when non-cgo builds are supported again.
        - cgo: "0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test
        env:
          CGO_ENABLED: ${{ matrix.cgo }}
        run: go test -v ${{ matrix.flags }} ./...
